# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: link/link.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flink/link.proto\"\xb8\x01\n\x04Link\x12\x17\n\x04type\x18\x01 \x01(\x0e\x32\t.LinkType\x12\x0f\n\x07link_id\x18\x02 \x01(\x05\x12\x16\n\x0esource_node_id\x18\x03 \x01(\x05\x12\x16\n\x0etarget_node_id\x18\x04 \x01(\x05\x12\x19\n\x11source_iface_name\x18\x05 \x01(\t\x12\x19\n\x11target_iface_name\x18\x06 \x01(\t\x12\x11\n\tbandwidth\x18\x07 \x01(\x02\x12\r\n\x05\x64\x65lay\x18\x08 \x01(\x02*S\n\x08LinkType\x12\"\n\x1eLINK_TYPE_INTER_SATELLITE_LINK\x10\x00\x12#\n\x1fLINK_TYPE_GROUND_SATELLITE_LINK\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'link.link_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LINKTYPE._serialized_start=206
  _LINKTYPE._serialized_end=289
  _LINK._serialized_start=20
  _LINK._serialized_end=204
# @@protoc_insertion_point(module_scope)
